title: "Friteegg"
description: "This is my personal website."
baseurl: ""
url: ""

lowercase: false
color_bg: var(--oc-gray-9)
color_punct: var(--oc-pink-9)
color_keyval: var(--oc-gray-9)
color_hover: var(--oc-pink-5)
show_quotes: false
show_commas: false
target: "_self"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
